# -*- coding: utf-8 -*-
"""SoumyaBanerjee

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1REDwEN5nnU0uBmduyNCu3WDGePKuzIHx

#Basic Coding Questions
"""

# Problem statement 01

filenames = ['view.jpg', 'bear.jpg', 'ball.png']
filenames.insert(0, 'phone.jpg')
if 'ball.png' in filenames:
    filenames.remove('ball.png')
print(filenames)

# Problem statement 02

L = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
max = L[0]
for num in L:
    if num > max:
        max = num
min = L[0]
for num in L:
    if num < min:
        min = num
total = 0
for num in L:
    total += num
average = total / len(L)
print("Maximum:", max)
print("Minimum:", min)
print("Average:", average)

"""#Inbuilt Data Structures

Intermediate Coding Questions
"""

# Problem Statement 01

L = [1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 4, 5]
unique_elements = []
for num in L:
    if num not in unique_elements:
        unique_elements.append(num)
print("Unique List:", unique_elements)

# Problem statement 02

L = [1, 2, 3, 4, [4, 3]]
number_to_check = 4
for element in L:
    if isinstance(element, list):
        if number_to_check in element:
            print(f"The number {number_to_check} exists in the inner list.")
            break
else:
    print(f"The number {number_to_check} does not exist in the inner list.")



"""# Advanced Coding questions"""

# Problem statement 01

numbers_nested = [[1, -1, 2], [0, -5, 3, 5, -2], [1, 2, 1, 0, -2, -3]]

positive_numbers = []
for nested_list in numbers_nested:
    for num in nested_list:
        if num > 0:
            positive_numbers.append(num)
print("Positive numbers:")
print(positive_numbers)

# Problem statement 02

L = [[1, 2, 3], [4, 5, 6, 3], [-1, -2, -10, 5, 8]]

averages = []
for inner_list in L:
    average_sum = sum(inner_list) / len(inner_list)
    averages.append(average_sum)
sum_of_averages = sum(averages)
print("Average sums:")
for average in averages:
    print(average)
print("Sum of averages:", sum_of_averages)

L = [[1, 2, 3], [4, 5, 6, 3], [-1, -2, -10, 5, 8]]

sum_of_averages = 0

for inner_list in L:
    average_sum = sum(inner_list) / len(inner_list)
    sum_of_averages += average_sum
print("Sum of average sums:", sum_of_averages)